export enum Types {
  TEXT = 'TEXT',
  CHECK_BOX = 'CHECK_BOX',
  RADIO_BUTTON = 'RADIO_BUTTON',
  POSITIVE_NUMBER = 'POSITIVE_NUMBER',
  NEGATIVE_NUMBER = 'NEGATIVE_NUMBER',
  DATE_TIME = 'DATE_TIME',
  SELECT = 'SELECT',
  ARRAY = 'ARRAY',
  OBJECT = 'OBJECT',
  MULTI_SELECT = 'MULTI_SELECT',
  MULTI_CHECKBOX = 'MULTI_CHECKBOX',
}
